Repository wei/socialify, pull requests merged in 2020-09, with the labels that each got.

#9 ⚡️ Create badges
  src/components/preview/badge.css
  src/components/preview/badge.tsx
  src/components/preview/card.css
  src/components/preview/card.tsx
Labels: enhancement

#15 🐛 Always display the badge options
  src/components/configuration/config.tsx
Labels: bug

#17 💄 Better error handling and display
  src/App.css
  src/components/mainRenderer.tsx
  src/components/mainWrapper.tsx
  src/components/repo/repo.tsx
Labels: enhancement

#19 💄 Mobile Styles Tweaks
  functions/image.js
  src/App.css
  src/App.tsx
  src/components/footer/footer.css
  src/components/footer/footer.tsx
  src/components/header/header.css
  src/components/header/header.tsx
  src/components/mainWrapper.css
  src/components/mainWrapper.tsx
  src/components/preview/card.css
  src/components/preview/preview.css
  src/components/repo/repo.css
  src/components/repo/repo.tsx
  src/index.css
  src/typings/react-app-env.d.ts
Labels: enhancement

#24 💄 Truncating description and name
  src/components/preview/card.css
  src/components/preview/card.tsx
  src/components/preview/preview-helpers.ts
Labels: enhancement

#27 ♿️ Improve accessibility
  src/App.tsx
  src/components/configuration/checkBoxWrapper.tsx
  src/components/configuration/config.css
  src/components/configuration/selectWrapper.tsx
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/repo/repo.tsx
Labels: enhancement

#30 🚨 Add prettier and eslint commit hooks
  .github/workflows/build.yml
  .prettierignore
  README.md
  package.json
  src/components/preview/badge.css
  src/components/preview/card.css
  src/index.css
  tsconfig.json
  yarn.lock
Labels: enhancement

#32 🔧 Changed default settings
  .prettierignore
  src/components/configuration/config.tsx
  src/components/mainWrapper.tsx
Labels: enhancement

#34 📝 Update Readme - Added Netlify cli as dev dependecy
  README.md
  package.json
  yarn.lock
Labels: documentation

#40 💄 Add favicon
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: enhancement

#45 💄 Update header design
  src/App.css
  src/App.tsx
  src/components/footer/__snapshots__/footer.test.tsx.snap
  src/components/footer/footer.tsx
  src/components/header/__snapshots__/header.test.tsx.snap
  src/components/header/header.css
  src/components/header/header.test.tsx
  src/components/header/header.tsx
  src/components/mainWrapper.css
  src/components/preview/preview.css
  src/index.css
Labels: enhancement

#50 ✨ Back and Forward Buttons
  package.json
  src/components/configuration/config.tsx
  src/components/configuration/textAreaWrapper.tsx
  src/types/configType.ts
  yarn.lock
Labels: enhancement
